openapi: 3.0.1
info:
  title: LogXMLPayloadAPI
  description: API Definition of LogXMLPayloadAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/logxml
paths:
  /payload:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /payloadxml:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/xml:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
